### ISSUE TITLE
Can't log in

### ISSUE THREAD

**Issue by WinterMute** [Digitalroot/MediaWiki_PHPBB_Auth#65]
I'm struggling to get this plugin to work although I did have a version working with mediawiki 1.28 before migrating hosts & upgrading wiki & forum.

Attempting to login with valid username/password leads to a page which says

```
wiki/Special:PluggableAuthLogin

There is currently no text in this page. You can search for this page title in other pages, or search the related logs), but you do not have permission to create this page.
```

Any help/hints would be appreciated

Using these versions of installed software
- MediaWiki 1.35
- PHP 7.4.33
- MySQL 10.5.19-MariaDB-0+deb11u2
- phpBB 3.3.10
- MediaWiki_PHPBB_Auth 4.1.0
- PluggableAuth 7.0.0 ( PluggableAuth-REL1_40-8104ed9 )

Have also tried PluggableAuth-REL1_35-cf04712 with the same result.

I have this at the top of the file but no logs are written

```
$wgDebugLogGroups = [
    "Auth_phpBB" => "/var/www/sites/logs/mw-debug-Auth_phpBB.log",
];

$wgShowExceptionDetails = true;
$wgShowDBErrorBacktrace = true;
$wgShowSQLErrors = true;```

```
    $wgAuth_Config = [
    //=======================================================================
    // Required settings

    'PathToPHPBB'  => '../',        // Path from this file to your phpBB install
    'UserTB'       => 'phpbb_users',      // Name of your phpBB user table
    'GroupsTB'     => 'phpbb_groups',     // Name of your phpBB groups table
    'User_GroupTB' => 'phpbb_user_group', // Name of your phpBB user_group table

    // Make MediaWiki usernames match the case of the phpBB usernames (except
    // with the first letter set to uppercase). Setting this to false causes
    // usernames to be all lowercase except for the first character.
    // NOTE: Before June 2016 this setting was always false, changing it to
    // true on an install where it previously was false will cause users with
    // uppercase characters to appear as separate users from their previous
    // all-lowercase account!
    'UseCanonicalCase' => true,

    //=======================================================================
    // Optional settings

    // --------------------------------------
    // Wiki Group settings
    // By default, any valid phpBB user can log in. To require the user to be
    // a member of one or more phpBB groups, set this to true.
    'UseWikiGroup'  => true,

    // phpBB group(s) the plugin checks for membership in when using
    // UseWikiGroup = true. Additional groups can be specified by adding
    // to the array: ['Wiki', 'SecondGroup']. To log in, the user must be
    // a member of at least one of them.
    'WikiGroupName' => ['Wiki'],

    // --------------------------------------
    // External database settings

    // Auth_phpBB assumes the phpBB tables are in the same database as the
    // MediaWiki tables. If phpBB is installed in a different MySQL database,
    // whether on the same or different host, set these parameters to have
    // the plugin connect to that database instead. See the config.php file
    // in your phpBB installation for the values.
    'UseExtDatabase' => true,
    'MySQL_Host'     => 'localhost',
    'MySQL_Port'     => '',
    'MySQL_Database' => '<prefix>_phpbb3',
    'MySQL_Username' => '<prefix>_phpbb3',
    'MySQL_Password' => '<password>',

    // --------------------------------------
    // Alternative username mappings

    // Use a custom username profile field in phpBB to create the username for
    // the wiki. This is most helpful for phpBB users whose usernames are
    // incompatible with MediaWiki username restrictions.
    // See the Auth_phpBB README.md for more information on configuring this.
    'UseWikiProfile'   => false,

    // Name of your phpBB profile data table.
    'ProfileDataTB'    => 'phpbb_profile_fields_data',

    // Name of your phpBB custom profile field.
    // phpBB prefixes 'pf_' to the custom field name you choose in the UI.
    // e.g., "wikiusername" becomes "pf_wikiusername"
    'ProfileFieldName' => 'pf_wikiusername',

    // --------------------------------------
    // Error messages

    // Error message to display to users on a failed login attempt.
    // Message text is formatted using wiki markup. An example with a link:
    // 'Please register on the [https://some.domain.com/phpbb forums] to login.'
    'LoginMessage' => 'Please register on the forums to login.',

    // Error message when a user is not a member of the required phpBB group
    'NoWikiError'  => 'You must be a member of the required forum group.',
    
    ];

**Comment by cpeel** [comment]
This plugin hasn't yet been tested with PluggableAuth 7.0 and it appears that it might require updates. I'd recommend trying one of the PluggableAuth 6.x releases.

Also check your `php_errors` file to see if there are any messages in there that might be helpful.

**Comment by cpeel** [comment]
Good lord they don't make this easy.
* `PluggableAuth-REL1_35-cf04712` is 5.7
* `PluggableAuth-REL1_39-1cbf448` is 7.0
* `PluggableAuth-REL1_40-8104ed9` is 7.0

I can see the 6.x series tagged at https://gerrit.wikimedia.org/g/mediawiki/extensions/PluggableAuth but I don't see an easy way of actually downloading that version. I've asked on the [discussions page](https://www.mediawiki.org/wiki/Topic:Xp27pcfm1m84oe6t) and am also working to get this plugin to support 7.0.

**Comment by cpeel** [comment]
Ok, here we go. If you download the `tgz` from the gerrit page for 6.3 you'll get that version of the repo which seems to be the same thing that the extension downloader gives you. Here's the link to [PluggableAuth 6.3](https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/extensions/PluggableAuth/+archive/c27f3296dc78fc5e54fc590eceb10da0c8d09309.tar.gz). That should work with MediaWiki 1.35 and the Auth_phpBB 4.1.0 release.

PluggableAuth 7.0 requires a version of MediaWiki I don't have ready access to right now so it's non-trivial for me to test an upgrade.

**Comment by cpeel** [comment]
Alternatively, you should be able to use PluggableAuth 5.7 with the Auth_phpBB 4.0.0 release on MediaWiki 1.35.

**Comment by mattheimer** [comment]
The following combination is working for me:

Auth_phpBB 4.1.0
PluggableAuth 7.1.0 (b8e2e84) 18:34, 15 June 2024
MediaWiki 1.39.7
PHP 7.4.3
phpBB 3.3.12

**Comment by cpeel** [comment]
Thanks @mattheimer.

@WinterMute if you're still having problems please open a new issue after trying the above.
